"""add work_services

Revision ID: 285290c62aff
Revises: 78edcb14dd38
Create Date: 2026-07-17 13:44:10.641625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285290c62aff'
down_revision: Union[str, None] = '78edcb14dd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'service_id', name='uix_work_service')
    )
    op.create_index(op.f('ix_work_services_id'), 'work_services', ['id'], unique=False)

    # Миграция существующих данных: одна услуга на работу
    op.execute("""
        INSERT INTO work_services (work_id, service_id, quantity, unit_price, total_price)
        SELECT id, service_id, service_quantity, service_unit_price, service_total_price
        FROM works
        WHERE service_id IS NOT NULL
    """)

    op.drop_constraint('works_service_id_fkey', 'works', type_='foreignkey')
    op.drop_column('works', 'service_id')
    op.drop_column('works', 'service_total_price')
    op.drop_column('works', 'service_quantity')
    op.drop_column('works', 'service_unit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('service_unit_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('service_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('service_total_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('works', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('works_service_id_fkey', 'works', 'services', ['service_id'], ['id'])
    op.drop_index(op.f('ix_work_services_id'), table_name='work_services')
    op.drop_table('work_services')
    # ### end Alembic commands ###
