"""add_request_completed_at

Revision ID: 4e8ae5818313
Revises: 8175d2e819cf
Create Date: 2026-08-19 09:50:45.220745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8ae5818313'
down_revision: Union[str, None] = '8175d2e819cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # Заполняем completed_at для уже завершённых заявок: предпочитаем updated_at, иначе created_at
    op.execute(
        sa.text(
            "UPDATE requests SET completed_at = COALESCE(updated_at, created_at) "
            "WHERE status = 'completed' AND completed_at IS NULL"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'completed_at')
    # ### end Alembic commands ###
