"""add request_id to works and service_id to requests

Revision ID: e6fe89dff18d
Revises: 79cb2fc8a727
Create Date: 2026-07-17 10:15:42.096799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6fe89dff18d'
down_revision: Union[str, None] = '79cb2fc8a727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_subscriptions_user_id', table_name='push_subscriptions')
    op.add_column('requests', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'services', ['service_id'], ['id'])
    op.add_column('works', sa.Column('request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'works', 'requests', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'request_id')
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'service_id')
    op.create_index('ix_push_subscriptions_user_id', 'push_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###
